Add combined value curve option
recurve-inc/flexvalue pull request #7
Opened 2023-07-11 17:37 UTC by keasey-recurve

### Your checklist for this pull request

Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a feature/bugfix branch** (right side). Don't request your master!
- [ ] Make sure tests pass and coverage has not fallen `./test.sh`.
- [ ] Update the [CHANGELOG.md](../CHANGELOG.md) to describe your changes in a bulleted list under the "Development" section at the top of the changelog. If this section does not exist, create it.
- [ ] Make sure code style follows PEP 008 using `black`.
- [ ] Make sure that new functions and classes have inline docstrings.

### Description

\<description of pull request (suggestion: start by copying from your changelog update and elaborate if necessary.)>

2023-08-02 22:30 UTC, keasey-recurve commented on flexvalue/templates/calculation.sql
> +    JOIN
@mattwyatt-recurve I'm doing some pre filtering here, not sure if it's really necessary or good form.

2023-08-02 22:31 UTC, keasey-recurve commented on flexvalue/templates/calculation.sql
> +    {% for field in elec_addl_fields if not field == "datetime" -%}
@mattwyatt-recurve  I standardized some of the naming conventions here because it was different between files.

2023-08-02 22:59 UTC, mattwyatt-recurve requested changes
There are a few things to address, but overall this looks really close.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on conftest.py
> +import requests as re
Please change this, as python already has an `re` module (for regular expressions) in the standard library, and I think this would be confusing to read.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/db.py
> +
Is this just whitespace? If so, please take it out.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/db.py
> +                x.get("value_curve_name"),
Why are you using `.get()` here? I thought you changed the schema to always require `value_curve_name`.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/calculation.sql
> +    JOIN
I don't think it's necessary; I think that `JOIN` handles this already. Have you tried it with and without, to see if there's any performance difference? Unless there's a compelling reason to keep it in (which would surprise me, I do think that `JOIN` handles this), I'd take it out.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/calculation.sql
> +    {% for field in elec_addl_fields if not field == "datetime" -%}
Nice.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/calculation.sql
> +    {% for field in elec_addl_fields if not field == "datetime" -%}
Why is `datetime` treated differently?

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/calculation.sql
> +      {% if use_value_curve_name_for_join -%}
Again, unless we have conclusive experimental evidence that this provides a performance benefit, this should be taken out.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/calculation.sql
> +, COALESCE(SUM(gas_calculations.lifecyle_net_therms_savings), 0) as lifecycle_net_therms_savings
Well this is weird. What changed here?

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/elec_calculation.sql
> +        (SELECT * FROM {{ eac_table }} WHERE value_curve_name IN (SELECT DISTINCT value_curve_name FROM project_costs)) elec_av_costs
As in other file, unless we know this is a benefit, we should take it out.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/gas_calculation.sql
> +      {% if use_value_curve_name_for_join -%}
As above, unless we know this is a benefit, we should take it out.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on flexvalue/templates/gas_calculation.sql
> +, SUM(gas_calculations.lifecyle_net_therms_savings) as lifecycle_net_therms_savings
Oh it's a missing 'c'! Can we fix that in `gas_calculations` also? How embarrassing that I never caught that.

2023-08-02 22:59 UTC, mattwyatt-recurve commented on tests/test_bq.py
Should you add a test for time-series outputs as well?

2023-08-03 00:27 UTC, keasey-recurve commented on flexvalue/templates/calculation.sql
> +    {% for field in elec_addl_fields if not field == "datetime" -%}
This was actually in the code already for the elec_calculations template. I assumed you were doing it for a reason so I just made them identical but bring it to the calculations template.

2023-08-03 00:27 UTC, keasey-recurve commented on flexvalue/templates/calculation.sql
> +      {% if use_value_curve_name_for_join -%}
Removed.

2023-08-03 00:27 UTC, keasey-recurve commented on flexvalue/templates/elec_calculation.sql
> +        (SELECT * FROM {{ eac_table }} WHERE value_curve_name IN (SELECT DISTINCT value_curve_name FROM project_costs)) elec_av_costs
Removed

2023-08-03 00:27 UTC, keasey-recurve commented on flexvalue/templates/gas_calculation.sql
> +      {% if use_value_curve_name_for_join -%}
removed

2023-08-03 00:27 UTC, keasey-recurve commented on tests/test_bq.py
I'm not too concerned about the time series if we're getting the electric/gas benefits that expect. If there's something explicit at the time series that we would test let me know though. It seems like adding in hour of year as an aggregation column or something would moreso be a test of the aggregation functionality which we already know is working well.

2023-08-03 00:28 UTC, keasey-recurve commented on conftest.py
> +import requests as re
Good call, updated.

2023-08-03 00:28 UTC, mattwyatt-recurve commented on flexvalue/db.py
> +
Nah, keep it. The diff made it look different, sorry.

2023-08-03 00:29 UTC, mattwyatt-recurve commented on tests/test_bq.py
Yeah it's hard to see how we'd get the aggregate results if the time series didn't add up properly.

2023-08-03 00:30 UTC, mattwyatt-recurve commented on flexvalue/templates/calculation.sql
> +    {% for field in elec_addl_fields if not field == "datetime" -%}
Ah, ok that sounds familiar. Thanks for the clarification.

2023-08-03 12:08 UTC, keasey-recurve commented
Feedback incorporated, merging into main.

2023-08-03 12:09 UTC, merged